language: java
jdk:
- oraclejdk8

env:
  global:
    - secure: "n3lO3QF+DOGYGRO/8UYbCRR1sUD024zUOGKlZyVZgMnyq/vKzlSEuGwM5MOa2tGUMyMM+pDekroMLuzAylXzhWUENHkBkrkbLzlhWCdqjw/ZKqc9ssoCcre9ffCQy6RPUGTVFxeoCj0IyvYfboO/ltNlsRW7KGHXE1gucEMIuieL8vI+0j6LwXRq7Uq869oz2npT7rrU7tShoQPGeRols2I3UPCEgCzABvgv8apmkGPJ4SwOU0ZMvBUGMKkPPwQPoGgHKxiOTEmjdXeWS4M2OhSTP4qUnLbb1NE9pITwWqpgKGoURydm28zV5hPHXuwrhpb49ccV8quNaQgJTjwZCdoU+l+hquiIJQwftf+OehmaFYPLSrVK9ss1Gl1q2wrbPfhbwyjBTPK57dRa9T4OUYf3C/L18xmDCWGEE1JXg3e1oRuuyE27Cp4p5OaSzNE0JzanAmW1IxiYDnt3ksGIJYQLVMYO+sT7dIEtmDxNxok/9arPgeQ+0lwbkP6M9MRcA0qdpalfRnGlN0dc/niPZBkBq+0gGebBnZgz/dPh4oH6/pemHMgTRUu00SwUCdhbWe/bxQhQaYWnIBlMxjmxZP9I80UBjw7BK1wcyUplSETTaw6RE/FA6edAjRIPcbVu/xe2KTBOAzvusJqoQEs3SchTXasZG8+2oRKvX+sjxUE="
    - secure: "vmjMMZG38igsNlPFQWLW/NlmmF37237kXqu1nJB9ZV1jnmdnCLyq+YIm8sd6lqeaeq2oERQe6fGLpYh20RvkC1QkKqfpnHCfKr2rlGf5r/xXIfPlFxnKad1S9g7ied3VrKnAoThUGBOJ7SN9bLUZ/OTeZ6ZP7ua/GPKk4x6Yve1j2YQIYgQ8Re3l11H0GBgwxCCcfgRPJtZrWqec7WfnYuwSFoKuyUJ/wGPyIT2L2tUsY5yEHn6BCyRz4dKSMfl9Zu8gEDOFZixn/bfT2yLqnXxkzk3gyqOQX0LHPyEp3XZnQVjF/3AGBeftg8meYbVWZ5eN9ADdjlBm/ZJHk9c3yNXea23GivkYPP1H36F6yfMSwUmjNKe+F/fk8Ay98SgRvUjE8D3rnkdUEcIiJYDZpPZgiujmD7WX3Kv8mhY8NkvKp1BO+rDXawHbOt3IK/eMxGbBSqCNlRTOT2J3TPhWi/RpVVtmpLqaqU2ebkXr9XWaVar1CSLaWvQN04lVEvXCmAtajbQslhFknzbqIztfpIDOoaB3ATFRUxjA4yHNMtZuaLAoiAm9uQMUrf9dr/YqdODaEoSQzdoNTA99inO7zComsvljClS8g6SkVTEcYbeZPPeTrtKJFTXAGHpdzksBt84pmzskf8zIa2/76MVv4ovaC93j0mykeztj8vg4sjE="

script:
  - ./gradlew clean check

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle

branches:
  except:
    - gh-pages

deploy:
- provider: script
  script: ./gradlew build bintrayUpload -PdryRun=false
  on:
    branch: master
    tags: true