language: java
jdk:
- oraclejdk8

cache:
  directories:
  - $HOME/.gradle

env:
  global:
#  - secure: E2jm3qJrcyavBwWkBQxqKrLjprl4QRT3vGtX87HyEzCYAveh+bdiY+gvu0q+RoFhAklzSEJnND5vBDbHD4gzV9bx9UdafrPzwKFEWt3ZcVGI70JEYHfcID0jzQ6pI7LismrTOpVkHyUZudBnG3yNh6PxID8890I5IMPHInvvVMUDhJ+jpLtjnn5HnRLVIEOX1A368pQoqiAKvSPuIHmDdFofYbAlgprWEtkrpdLd/1Yp95yrE5EjC6nwjhvG2LHiKTr5FgAWD9/owmemioBnexSxEgZe76cRm38WDQVWpEppp7FHJ7eo0LhtEBXYUXJX2UE6W5A0rRBfRRoOCa8eABmY2kxsm5TajlA7yrxqeQebuvcQzVmSjPJ3t7JLkgcYMI88HbpvKjhA5fFVi8TeThd85wXp58eQkIU/7EoLPaqALUHw8WCAaBOmcQ37MLeSk6oX8SQUS0owo58guh1SN95BpTrMuzvvN4V9LPGNMfnVBxuKjnfOxxPkBWLEsuvgGwdC9pYj3dDYVDD7igrGy5qTwTJ8qTtqud3uUY0JVzpPpN6m3IKI0qxEOYTDS3WrJh14P8flFZXYU/Vot1xkmZPMlAAqYxdRWLnNAjwS+c8VePKqZmIp3FVxFyrs9yJehFWynB0ZYi3ZUtc0UKkoIKLocMi1huHgAmRrJbteN9Y=

#deploy:
#- provider: script
#  skip_cleanup: true
#  script: ./gradlew build bintrayUpload -PdryRun=false
#  on:
#    branch: master
#    tags: true